### ISSUE TITLE
Lint errors in e2e/src/app.po.ts

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#106]
Fix the following 2 lint errors in _e2e/src/app.po.ts_

- [ ] ERROR: 4:3     typedef      expected call-signature: 'navigateTo' to have a typedef
- [ ] ERROR: 8:3     typedef      expected call-signature: 'getParagraphText' to have a typedef

**Comment by sjpcp5** [comment]
Fix the following 2 lint errors in e2e/src/app.po.ts

 [ x ] ERROR: 4:3 typedef expected call-signature: 'navigateTo' to have a typedef
 [ x ] ERROR: 8:3 typedef expected call-signature: 'getParagraphText' to have a typedef
