### ISSUE TITLE
There are lint errors in src/app/app.component.router.spec.ts and src/app/app.component.ts

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#107]
src/app/app.component.router.spec.ts:21:14
- [ ] WARNING: 21:14   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

src/app/app.component.spec.ts:9:14
- [ ] WARNING: 9:14    deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)
- [ ] WARNING: 24:31   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)
- [ ] WARNING: 28:86   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

**Comment by sjpcp5** [comment]
Working on this one 🔢
