### ISSUE TITLE
There are lint errors in FinancialAidComponent that need to be fixed

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#109]
src/app/financial-aid/financial-aid.component.spec.ts:9:14
- [ ] WARNING: 9:14    deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

src/app/financial-aid/financial-aid.component.ts:12:3
- [ ] ERROR: 12:3    typedef      expected call-signature: 'ngOnInit' to have a typedef

**Comment by sjpcp5** [comment]
Working on this one
src/app/financial-aid/financial-aid.component.spec.ts:9:14

- [] WARNING: 9:14 deprecation async is deprecated: use waitForAsync(), (expected removal in v12)
src/app/financial-aid/financial-aid.component.ts:12:3

- [] ERROR: 12:3 typedef expected call-signature: 'ngOnInit' to have a typedef
