### ISSUE TITLE
There are lint errors in Signup and Nav components

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#115]
src/app/home/signup/signup.component.spec.ts:30:14
- [ ] WARNING: 30:14   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

src/app/nav/nav.component.spec.ts:10:14
- [ ] WARNING: 10:14   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

src/app/nav/nav.component.ts:13:3
- [ ] ERROR: 13:3    typedef      expected call-signature: 'ngOnInit' to have a typedef

**Comment by sjpcp5** [comment]
Working on it 🔢
