### ISSUE TITLE
There are lint errors in Resoureces and Tools components that need to be fixed

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#117]
src/app/resources/resources.component.spec.ts:10:14
- [ ] WARNING: 10:14   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

src/app/resources/resources.component.ts:16:3
- [ ] ERROR: 16:3    typedef      expected call-signature: 'ngOnInit' to have a typedef

src/app/resources/tools/tools.component.spec.ts:10:14
- [ ] WARNING: 10:14   deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)

**Comment by Hyunsujk** [comment]
I want to work on this! @alisaduncan
