### ISSUE TITLE
There is an unnecessary header tag in the Contact Component

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#119]
Remove the `h5` tag and verify vertical spacing looks ok. Please add styles to fix spacing as needed.
https://github.com/KansasCityWomeninTechnology/cocktails-site/blob/73115c7e65cd8f737571d564435fd30f21317e10/src/app/contact/contact.component.html#L5

**Comment by sjpcp5** [comment]
I submitted a PR for this issue and be found under " remove unnecessary header tag (#119) "
