### ISSUE TITLE
The link in Contact Component isn't using https

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#121]
We should use https protocol in links where it's supported.

https://github.com/KansasCityWomeninTechnology/cocktails-site/blob/d7bfd371e949382380ca413385bdfde92ad2071b/src/app/contact/contact.component.html#L16

**Comment by Hyunsujk** [comment]
I want to work on this! @alisaduncan is changing from HTTP to https is all that needs to be done?

**Comment by alisaduncan** [comment]
@Hyunsujk sorry for the late response. Yup, that's all we need to do for this issue.

**Comment by Hyunsujk** [comment]
no worries! PR should be up soon :)

**Comment by Hyunsujk** [comment]
PR is open #130
