### ISSUE TITLE
The protocol for the links to xkcd and twitter should be https in Cocktails, Code, and Mentor component

### ISSUE THREAD

**Issue by alisaduncan** [KansasCityWomeninTechnology/cocktails-site#124]
There are 3 links to change, one in Cocktails component, one in Code component, and one in Mentor component.

Example link to line of code in Cocktails component below.
https://github.com/KansasCityWomeninTechnology/cocktails-site/blob/d7bfd371e949382380ca413385bdfde92ad2071b/src/app/home/cocktails/cocktails.component.html#L7

Links to Code component and Mentor component are not included in the issue, but they need to be fixed too.

**Comment by sniemeyer1** [comment]
On it!
